version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
aliases:
  - &restore-cache
    keys:
      - v2-dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}

  - &save-cache
    paths:
      - node_modules
    key: v2-dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}

  - &install npm ci

jobs:
  build:
    working_directory: ~/axios-layer
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run: *install
      - save_cache: *save-cache
      - run: npm run build

  test-node-10:
    working_directory: ~/axios-layer
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run: *install
      - save_cache: *save-cache
      - run:
          command: npm test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test-node-10
